import { Link } from 'react-router-dom';

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6 lg:px-10">
      <Link to="/" className="text-sm text-gold hover:underline">
        ← Back to heroes
      </Link>

      <h1 className="mt-4 text-2xl font-bold text-gold sm:text-3xl">Privacy Policy</h1>
      <p className="mt-1 text-sm text-gray-500">Last updated: August 18, 2026</p>

      <div className="mt-6 space-y-6 text-sm leading-relaxed text-gray-300">
        <p>
          Dota 2 Pick Helper ("the app", "we", "our") is a free, entertainment-focused, fan-made
          tool for Dota 2 players. It is not affiliated with, endorsed by, or sponsored by Valve
          Corporation. This page explains what data the app handles and how.
        </p>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">What we don't collect</h2>
          <p>
            The app has no user accounts, no sign-up, and no forms. We do not collect names,
            emails, or any other personal information from visitors. We do not use cookies for
            tracking, do not run analytics scripts, and do not serve ads.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">What we do collect</h2>
          <p>
            Like any web server, our hosting infrastructure keeps standard access logs (IP
            address, browser user-agent, requested page, timestamp) for a limited time, used only
            for operating and securing the service — never for advertising or profiling.
          </p>
          <p className="mt-2">
            The app has one administrative account, used only by the site operator to manage hero
            data and trigger analysis. Its password is stored as a salted cryptographic hash, not
            in plain text, and its login session is kept in your browser's local storage rather
            than a cookie.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">Third-party data sources</h2>
          <p>
            The app's server pulls public Dota 2 data from a few external sources to build its
            hero and patch information. None of these receive any personal data about you — the
            app only reads public data from them, it does not send them any visitor information:
          </p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>
              <span className="text-white">OpenDota</span> — public hero stats and professional
              match data.
            </li>
            <li>
              <span className="text-white">Valve (dota2.com)</span> — public patch notes.
            </li>
            <li>
              <span className="text-white">YouTube Data API</span> — public video titles and
              descriptions from a small, fixed set of Dota 2 content channels, used only to add
              context to hero write-ups.
            </li>
          </ul>
          <p className="mt-2">
            AI-written summaries are generated by a language model running on our own server —
            no visitor data is sent to any third-party AI service.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">Children's privacy</h2>
          <p>
            This app is not directed at children under 13 and we do not knowingly collect
            information from children.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">Changes to this policy</h2>
          <p>
            If how the app handles data changes meaningfully, this page will be updated with a
            new "last updated" date.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">Contact</h2>
          <p>
            Questions about this policy can be sent to{' '}
            <a href="mailto:mustafaguner235@gmail.com" className="text-gold hover:underline">
              mustafaguner235@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
